{
 "title": "Activity",
 "tags": [
  "prod",
  "dev"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "site", "query": "influxdb" }
  ]
 },
 "panels": [
  { "title": "Places, Pickups and Feedback", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active place cooperations",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.group.places",
     "query": "SELECT sum(\"pickup_done\") FROM \"karrot.events\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "count_status_active" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pickups done",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "query": "SELECT sum(\"pickup_done\") FROM \"karrot.events\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "pickup_done" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "!=", "value": "16" }
     ]
    }
   ]
  },
  {
   "title": "Feedback given",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "query": "SELECT sum(\"pickup_done\") FROM \"karrot.events\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "feedback" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pickups missed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "query": "SELECT sum(\"pickup_done\") FROM \"karrot.events\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "pickup_missed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "!=", "value": "16" }
     ]
    }
   ]
  },
  { "title": "Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Wall messages",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "query": "SELECT sum(\"pickup_done\") FROM \"karrot.events\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "group" },
      { "condition": "AND", "key": "is_reply", "operator": "!=", "value": "True" }
     ]
    }
   ]
  },
  {
   "title": "Replies",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 5 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "query": "SELECT sum(\"pickup_done\") FROM \"karrot.events\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "is_reply", "operator": "=", "value": "True" }
     ]
    }
   ]
  },
  {
   "title": "Pickup messages",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 5 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "query": "SELECT sum(\"pickup_done\") FROM \"karrot.events\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pickup" }
     ]
    }
   ]
  },
  {
   "title": "Application messages",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 5 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "query": "SELECT sum(\"pickup_done\") FROM \"karrot.events\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "application" }
     ]
    }
   ]
  },
  {
   "title": "Private messages",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "query": "SELECT sum(\"pickup_done\") FROM \"karrot.events\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "private" }
     ]
    }
   ]
  },
  {
   "title": "Reactions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 5 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "query": "SELECT sum(\"pickup_done\") FROM \"karrot.events\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "message_reaction" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Applications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Pending applications",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.group.applications",
     "select": [
      [
       { "params": [ "count_status_pending" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Accepted applications",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 9 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "select": [
      [
       { "params": [ "application_accepted" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Declined applications",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 9 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "select": [
      [
       { "params": [ "application_declined" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Withdrawn applications",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 9 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "select": [
      [
       { "params": [ "application_withdrawn" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Decided within (avg)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 9 },
   "format": "h",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "select": [
      [
       { "params": [ "application_alive_seconds" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ " / 3600" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  { "title": "Users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "New users",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "django_auth_user_create",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Group joins",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 13 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "select": [
      [
       { "params": [ "group_joined" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Group leaves",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 13 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "select": [
      [
       { "params": [ "group_left" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Marked as inactive in groups",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 13 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.periodic",
     "select": [
      [
       { "params": [ "count_users_flagged_inactive" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Tech stuff", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Websocket messages",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "select": [
      [
       { "params": [ "websocket_push" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Browser push messages",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 17 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "select": [
      [
       { "params": [ "subscription_push" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "platform", "operator": "=", "value": "web" }
     ]
    }
   ]
  },
  {
   "title": "Android push messages",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 17 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "select": [
      [
       { "params": [ "subscription_push" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "platform", "operator": "=", "value": "android" }
     ]
    }
   ]
  },
  {
   "title": "API requests",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 17 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "django_request",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "API read reponse time (slow)",
   "type": "singlestat",
   "description": "1% of slowest read requests, averaged",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 17 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "django_request",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "99" ], "type": "percentile" }
      ]
     ],
     "tags": [
      { "key": "method", "operator": "=", "value": "GET" }
     ]
    }
   ]
  },
  {
   "title": "Emails sent",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 20 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.email.sent",
     "select": [
      [
       { "params": [ "recipient_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Emails errors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 20 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.email.error",
     "select": [
      [
       { "params": [ "recipient_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "User activity",
   "type": "singlestat",
   "description": "Arbitrary number that roughly correlates with the time the user spends clicking around",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 20 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "select": [
      [
       { "params": [ "group_activity" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "API write reponse time (slow)",
   "type": "singlestat",
   "description": "1% of slowest requests, averaged",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 20 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "django_request",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "99" ], "type": "percentile" }
      ]
     ],
     "tags": [
      { "key": "method", "operator": "=", "value": "PATCH" },
      { "condition": "OR", "key": "method", "operator": "=", "value": "POST" },
      { "condition": "OR", "key": "method", "operator": "=", "value": "PUT" },
      { "condition": "OR", "key": "method", "operator": "=", "value": "DELETE" }
     ]
    }
   ]
  },
  {
   "title": "Group leaderboard",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "group" ], "type": "tag" }
     ],
     "measurement": "karrot.events",
     "query": "SELECT sum(\"group_activity\") AS \"page impressions\", sum(\"pickup_joined\") AS \"pickups joined\", sum(\"pickup_done\") AS \"pickups done\", sum(\"pickup_missed\") AS \"pickups missed\", sum(\"feedback\") AS \"feedbacks given\", sum(\"message\") AS \"messages written\", sum(\"message_reaction\") AS \"message reactions\", sum(\"group_joined\") AS \"new members\" FROM \"karrot.events\" WHERE $timeFilter GROUP BY \"group\"",
     "select": [
      [
       { "params": [ "group_activity" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "activity" ], "type": "alias" }
      ],
      [
       { "params": [ "message_reaction" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "reactions" ], "type": "alias" }
      ],
      [
       { "params": [ "pickup_joined" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "pickups joined" ], "type": "alias" }
      ],
      [
       { "params": [ "group_joined" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "members joined" ], "type": "alias" }
      ],
      [
       { "params": [ "pickup_done" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "pickups done" ], "type": "alias" }
      ],
      [
       { "params": [ "pickup_missed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "pickups missed" ], "type": "alias" }
      ],
      [
       { "params": [ "feedback" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "feedback" ], "type": "alias" }
      ],
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "messages" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active in last week (with >3 active users)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "group $tag_group",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "group" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "karrot.group.members",
     "select": [
      [
       { "params": [ "count_active_7d" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "count_active_7d", "operator": ">", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "Group Names",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT id, name FROM group_names"
    }
   ]
  },
  {
   "title": "Group Activity",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "group" ], "type": "tag" }
     ],
     "measurement": "karrot.group.members",
     "select": [
      [
       { "params": [ "count_total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "total" ], "type": "alias" }
      ],
      [
       { "params": [ "count_active_1d" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "active last 1d" ], "type": "alias" }
      ],
      [
       { "params": [ "count_active_7d" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "active last 7d" ], "type": "alias" }
      ],
      [
       { "params": [ "count_active_30d" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "active last 30d" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pickups by group",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "alias": "group $tag_group $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "group" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "select": [
      [
       { "params": [ "pickup_done" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "pickup done" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "group $tag_group $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "group" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "select": [
      [
       { "params": [ "pickup_missed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "pickup missed" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pickups",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 61 },
   "yaxes": [
    { "format": "short", "label": "Count (stacked)" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "select": [
      [
       { "params": [ "pickup_done" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "pickup done" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "karrot.events",
     "select": [
      [
       { "params": [ "pickup_missed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "pickup missed" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Group messages",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 61 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "group" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" }
     ],
     "measurement": "karrot.events",
     "select": [
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "messages" ], "type": "alias" }
      ],
      [
       { "params": [ "message_reaction" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "reactions" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Emails sent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "recipient count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "karrot.email.sent",
     "select": [
      [
       { "params": [ "recipient_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pickup notification stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col [group=$tag_group]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "group" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "karrot.email.pickup_notification",
     "select": [
      [
       { "params": [ "tomorrow_empty" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "tomorrow empty" ], "type": "alias" }
      ],
      [
       { "params": [ "tomorrow_not_full" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "tomorrow not full" ], "type": "alias" }
      ],
      [
       { "params": [ "tomorrow_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "tomorrow user" ], "type": "alias" }
      ],
      [
       { "params": [ "tonight_empty" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "tonight empty" ], "type": "alias" }
      ],
      [
       { "params": [ "tonight_not_full" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "tonight not full" ], "type": "alias" }
      ],
      [
       { "params": [ "tonight_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "tonight user" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Group Summary notifications",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "group $tag_group $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "group" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "karrot.email.group_summary",
     "select": [
      [
       { "params": [ "email_recipient_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "recipients" ], "type": "alias" }
      ],
      [
       { "params": [ "feedback_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "feedback" ], "type": "alias" }
      ],
      [
       { "params": [ "message_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "messages" ], "type": "alias" }
      ],
      [
       { "params": [ "new_user_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "new users" ], "type": "alias" }
      ],
      [
       { "params": [ "pickups_done_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "pickups done" ], "type": "alias" }
      ],
      [
       { "params": [ "pickups_missed_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "pickups missed" ], "type": "alias" }
      ],
      [
       { "params": [ "pickups_missed_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "pickups missed" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Users marked as inactive",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "number of users",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "karrot.periodic",
     "select": [
      [
       { "params": [ "count_users_flagged_inactive" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "group__process_inactive_users" }
     ]
    }
   ]
  }
 ]
}